### ISSUE TITLE
Faux pollutes implementation blocks that are not mocked

### ISSUE THREAD

**Issue by cortopy** [nrxus/faux#44]
Not sure if if I'm using this crate ok, but given something like this:

```rust
#[cfg_attr(test, faux::create)]
pub struct MyStruct {
    pub something: i32,
}

impl MyStruct {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self { something: 3 })
    }
}
```

I get the error ```struct `subscriber::MyStruct` has no field named `something` field does not exist``` in the unmocked `MyStruct::new` function

If I try to mock the `impl` too like:

```
#[cfg_attr(test, faux::methods)]
impl MyStruct {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self { something: 3 })
    }
}
```

I get the error 
```
mismatched types
expected enum `std::result::Result<mymodule::MyStruct, _>`
   found enum `std::result::Result<mymodule::_FauxOriginal_MyStruct, _>`
```

in the `faux::methods` proc attribute

**Comment by nrxus** [comment]
Hi,

This is expected behavior. Once a struct has been tagged with `faux::create`, any function that refers to its fields needs to be in an `impl` block that is tagged by `faux::methods`.

In your first example `new` is referring to the field `something` when trying to create that struct but it fails because the `impl` block is not tagged by `faux::methods`.

I called this out in the [docs for faux::create](https://docs.rs/faux/0.1.3/faux/attr.create.html#requirements) but I understand maybe that was too hidden. 

The second example is slightly trickier and I tried to call out for this in [these docs](https://docs.rs/faux/0.1.3/faux/attr.methods.html#returning-mockable-struct). But again I understand that api docs are not the most searchable thing, especially as you start digging outside of the root docs. In summary the workaround for this is to have two functions. The one that returns `Self` is inside an `impl` block tagged by `faux::methods`. The one that returns `Result<Self, Error>` is in an `impl` not tagged by `faux::methods` and just prxoies to the former function after all of the fallible stuff have been resolved. 

```rust
#[cfg_attr(test, faux::create)]
pub struct MyStruct {
    pub something: i32,
}

#[cfg_attr(test, faux::create)]
impl MyStruct {
    fn private_new(something: i32) -> Self {
        MyStruct { something }
    }
}

impl MyStruct {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        let something = load_something()?;
        Ok(Self::private_new(something))
    }
}
``` 

This avoids the issue because `new()` doesn't refer to the struct fields directly, and `private_new` returns `Self` not wrapped in `Result`.

I think it may be possible for `faux` to get around this for things that return `Result` and maybe even `Option` but it would be tricky so I haven't prioritized it yet, but I can take a look at it. For now this is expected behavior however. 

In your opinion, where would it have been best for this to be documented so it would have been more accessible?

**Comment by cortopy** [comment]
Thanks @nrxus for looking into this!

Sadly, I've tried the example you've given and it doesn't work for me.

For this one
```rust
#[cfg_attr(test, faux::create)]
impl MyStruct {
    fn private_new(something: i32) -> Self {
        MyStruct { something }
    }
}
```

error says that `faux::create` expects a struct not a `impl` block. If I change it to `faux:methods` then I've gone back to square 1, as it complains that `return type should not be Self`

As for the docs, I find crates with a lot of examples very helpful. For example, the [tonic](https://github.com/hyperium/tonic/tree/master/examples/src) crate has so many that I've always found something that would tell me how to do it and/or where to look

**Comment by nrxus** [comment]
As I misspoke in my last comment. Do `faux::methods` in the `impl` block.

**Comment by nrxus** [comment]
I added a test in: https://github.com/nrxus/faux/blob/f317aab3ab11baf4bf19047896d05bc28f53e658/tests/simple.rs#L35-L40

This proves that it can be done. I have been adding this kind of things inside the crate integration `tests` rather than examples since I view them as proving that the library works, not just examples on how to use them. Although maybe adding something on examples would also be helpful, I'll think about it (: 

Let me know if this solves your issue.

**Comment by cortopy** [comment]
that's great! thanks a lot
