### ISSUE TITLE
The newest release(0.1.4) MSRV should raise to 1.54

### ISSUE THREAD

**Issue by zhangsoledad** [nrxus/faux#45]
Since the newest release(0.1.4) use 

```
 #[doc = include_str!("../README.md")]
```

https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#attributes-can-invoke-function-like-macros.

**Comment by nrxus** [comment]
Ah! 🤦🏾 

I naively thought that because I only use that for `docs` that it would be fine. Ideally I should have a CI step that runs `cargo check` on the MSRV but I haven't gotten around that yet. PRs welcome though (:

I just released version 0.1.5 that moves `#[doc = include_str!("../README.md")]` into its own gated module so no one depending on `faux` has to be on such a high version. I may yank version 0.1.4 since I am not sure if bumping the MSRV is a breaking change or not. 

Thanks for bringing this up!
