### ISSUE TITLE
bug on trying to access to a field but rust-analyzer fails. 

### ISSUE THREAD

**Issue by lauti7** [nrxus/faux#52]
Hi! I have a struct with the `faux::create` attribute and the `faux::methods` in its implementation blocks, but when I try to access the struct's fields, VSCode in this case, it's not displaying the available fields. It only shows the field `0` and the struct methods. 

Despite this, the code runs and compiles well. But I'm not sure why, is there any runtime cost when using faux? 

the example below: 

Here it's the struct and then the VSCode screenshot: 
```rust
#[cfg_attr(test, faux::create)]
#[derive(Clone)]
pub struct DatabaseComponent {
    db_host: String,
    db_user: String,
    db_password: String,
    db_name: String,
    db_connection: Arc<Option<DBConnection>>,
    pub db_repos: Option<DBRepositories>,
}

#[cfg_attr(test, faux::methods)]
impl DatabaseComponent {
    pub fn new(db_config: &DatabaseConfig) -> Self {
        Self {
            db_host: db_config.host.clone(),
            db_user: db_config.user.clone(),
            db_password: db_config.password.clone(),
            db_name: db_config.name.clone(),
            db_connection: Arc::new(None),
            db_repos: None,
        }
    }

    pub async fn run(&mut self) -> Result<(), sqlx::Error> {
       //.... not important stuff
    }
}

```

`Data<AppComponents>` it's an `Arc` that has `AppComponents` which owns the `DatabaseComponent` struct, and its unique `pub` field doesn't appear when u trying to access it. 

![Screen Shot 2022-12-16 at 12 42 52](https://user-images.githubusercontent.com/26555310/208135094-943cc414-212c-422b-9639-48e97aae9fdd.png)

**Hope u can help me out and have a workaround to have a better developer experience.**

**Comment by schneidersteve** [comment]
My workaround for the next years is to mock no struct but only traits with the mockall crate and the mock! macro. In some cases i need a real implementation in my tests.

**Comment by lauti7** [comment]
@schneidersteve Thx for your response but I don't want to use the `mockall` crate, I don't like its solution with traits because in order to do something similar to what `faux` does, you have to use `dyn` objects or spread generics all around your service. I've used `mockall` but I switch to `faux` crate.

Maybe @nrxus has or can come up with a workaround for the rust-analyzer issue

**Comment by nrxus** [comment]
Hey @lauti7, a couple of things here:

>  is there any runtime cost when using faux?

There is zero runtime cost when running code outside of tests. This is guaranteed because:
* Your dependency on `faux` should only ever be in the `dev-dependencies` section in your `Cargo.toml` so when running your code outside of "dev mode" (e.g., not in tests) `faux` doesn't even exist anywhere in your compiled code. 

* The macros are gated using `#[cfg_attr(test, ...)]` meaning that the macros are only expanded in test code so `faux` doesn't run at all outside of tests even if you by accident added `faux` as a real dependency rather than a dev dependency. 

Now onto why does `vscode` not show your struct fields: `rust-analyzer` always compiles with the test configuration on so it can provide assistance on your test code. Because of this as far as `rust-analyzer` is aware the `DatabaseComponent` struct does not have those fields anymore because that struct was re-written to make it mockable under tests. The part I find weird is why are you trying to access fields of the struct directly? All those fields are private so you should only be trying to access the methods right? The methods should exist in the mocked struct so those should be showing up in vscode (I see the `is_connected()` method showing., The unfortunate part is that because `_` comes before any lowercase ascii character it gets sorted first which is unfortunate. I think `rust-analyzer` should prioritize any `_` methods/fields last as they are obviously not meant to be used publicly but that's outside of my control 😞 . I may file a feature request in rust analyzer to change the sort, or if I ever find free time again try to learn how it works and do my own PR 😅 . 

Hopefully this all made sense, let me know if I can help explain anything further. P.S. I see that you are located in Argentina, I am originally from Peru so I can try to explain it in castellano if that would help 😄 .

**Comment by lauti7** [comment]
@nrxus Okay got it! Thank you again for the quick response. Good to know more about how this works deeper. I was trying to access `db_repos` that it's the unique field public of `DatabaseComponent` but I understand now why it didn't even appear. I think the only solution possible is to use `getters/setters` (btw, I don't like that much).

Just to know: Do you have any workaround or another way to code so that you have a better developer experience? Or do you just keep coding with `rust-analyzer` errors? btw, Idk if it's possible to modify the way how `rust-analyzer` compiles the code. 

Nice to know that you are from Peru! I keep it in English for those who use the crate and looking for a solution to this issue.

**Comment by nrxus** [comment]
Ah I see the first thing I notice is that the check I used to have to prevent people from having public fields on mocked structs is gone, I don't quite remember when/why I removed it but I should put it back. Mocks and public fields don't go hand in hand (what should happen when you try to access a field of a mock instance?). So after I put that back your example will fail to compile (as expected) saying that all fields should be private. WIth `faux` I want to emphasize that mocking is for behavior not for data, when you make fields public you are saying "there is data inside this struct that should be viewable outside" so it is no longer just behavior and thus should not be mockable. I agree that setters/getters are not ideal but I think that's because you are leaking what is in my opinion an implementation detail of `DatabaseComponent`. I think a refactor of the code would make it better, although a getter just for that *one* field should be okay-ish. 

I haven't encountered those `rust-analyzer` errors before because I don't make public fields on stuff I am going to mock (since I thought I had made that a compile errors but apparently I removed that 🤷🏾 ). You could *try* to get around that by adding special feature flags for tests that use mocks and only activate `faux` when that feature flag is on. `rust-analyzer` wouldn't activate that flag so there wouldn't be any compiler errors. I wouldn't suggest doing it but it is technically feasible.
