### ISSUE TITLE
Third-party structs mocking

### ISSUE THREAD

**Issue by BogdanKosarev** [nrxus/faux#63]
Hi and thanks for `faux`!
Is there a way to mock a third-party struct? Should I write some kind of wrapper to achieve this?

**Comment by nrxus** [comment]
Wrappers are the way go-to. They both make it so that you can mock the wrapper, and convert the domain language from the third-party crate (e.g., some generic database driver) to your own domain language.

**Comment by BogdanKosarev** [comment]
Yes, sure - the pros of wrappers are clear.
But I also would prefer to avoid wrappers at least for some simple straight-forward cases where implementing a wrapper connected with lot of boilerplate code. 
So you don't have plans to add such features to `faux`?

**Comment by nrxus** [comment]
I do not, both because I subscribe to [do not mock what you don't own](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own), and also (perhaps more crucially) Rust makes this unfeasible. There is no way to hook a macro into an external dependency in a way that gives you the signature of all the methods inside their struct so that you can create mockable versions of them.
